[pass] Fix travis-ci error on internal link
problem:
The internal link:
-  See [[info:auth#The Unix password store][its info page]] for more details on using it.

Caused an issues with travis-ci:
https://travis-ci.org/github/syl20bnr/spacemacs/jobs/732236190#L332

error: Link "info:auth#The Unix password store" has unknown type "info"

Solution:
Linked to the same page in the online manual.